# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

#   encoders:
#    Symfony\Component\Security\Core\User\User: plaintext



    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:

#   entity: { class: FormBundle\Entity\person, property: login }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
#            provider:in_database
            form_login:
                login_path: security_login
                check_path: security_login
#                logout:
#                    path: security_logout
#                    target: inscription

#          role_hierarchy:
#               ROLE_ADMIN:       ROLE_USER
#              ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
