<?php

namespace FormBundle\Repository;

/**
 * adminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adminRepository extends \Doctrine\ORM\EntityRepository
{
}
