<?php

namespace FormBundle\Repository;

/**
 * formateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formateurRepository extends \Doctrine\ORM\EntityRepository
{
}
