<?php

namespace FormBundle\Repository;

/**
 * personRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personRepository extends \Doctrine\ORM\EntityRepository
{
}
