<?php

namespace FormBundle\Repository;

/**
 * personneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personneRepository extends \Doctrine\ORM\EntityRepository
{
}
